INSERT INTO FRAMEWORKS (ID, NAME, HYPE_LEVEL) VALUES(1, 'Angular', 10);
INSERT INTO FRAMEWORKS (ID, NAME, HYPE_LEVEL) VALUES(2, 'React', 9);
INSERT INTO FRAMEWORKS (ID, NAME, HYPE_LEVEL) VALUES(3, 'Vue', 8);

INSERT INTO FRAMEWORK_VERSIONS (FRAMEWORK_ID, VERSION, DEPRECATION_DATE) VALUES(1, '14.0.0', '2023-12-02');
INSERT INTO FRAMEWORK_VERSIONS (FRAMEWORK_ID, VERSION, DEPRECATION_DATE) VALUES(1, '13.0.0', '2023-05-04');
INSERT INTO FRAMEWORK_VERSIONS (FRAMEWORK_ID, VERSION, DEPRECATION_DATE) VALUES(2, '18.2.0', '2024-10-01');
INSERT INTO FRAMEWORK_VERSIONS (FRAMEWORK_ID, VERSION, DEPRECATION_DATE) VALUES(3, '3.2.37', '2023-12-01');
