INSERT INTO FRAMEWORKS (ID, NAME, DEPRECATION_DATE, HYPE_LEVEL) VALUES(1, 'Angular', '2023-12-02', 10);
INSERT INTO FRAMEWORKS (ID, NAME, DEPRECATION_DATE, HYPE_LEVEL) VALUES(2, 'React', '2024-10-01', 9);
INSERT INTO FRAMEWORKS (ID, NAME, DEPRECATION_DATE, HYPE_LEVEL) VALUES(3, 'Vue', '2023-12-01', 8);

INSERT INTO FRAMEWORK_VERSIONS (FRAMEWORK_ID, VERSION) VALUES(1, '14.0.0');
INSERT INTO FRAMEWORK_VERSIONS (FRAMEWORK_ID, VERSION) VALUES(1, '13.0.0');
INSERT INTO FRAMEWORK_VERSIONS (FRAMEWORK_ID, VERSION) VALUES(2, '18.2.0');
INSERT INTO FRAMEWORK_VERSIONS (FRAMEWORK_ID, VERSION) VALUES(3, '3.2.37');
